CREATE PROCEDURE [cmp].[spLoadSchoolDimension] (
	@OdsDatabaseReference nvarchar(512)
	) AS
DECLARE @sqlCmd nvarchar(max)
SET @sqlCmd = '
INSERT INTO [cmp].[SchoolDimension]
           ([SchoolKey]
           ,[NameOfInstitution]
           ,[StreetNumberName]
           ,[BuildingSiteNumber]
           ,[City]
           ,[StateAbbreviation]
           ,[PostalCode]
           ,[NameOfCounty]
           ,[MainInstitutionTelephone]
           ,[InstitutionFax]
           ,[WebSite]
           ,[PrincipalName]
           ,[PrincipalElectronicMailAddress]
           ,[GradeLevels]
           ,[AccreditationStatus]
           ,[LocalEducationAgencyKey]
           ,[LEANameOfInstitution]
           ,[LEAStreetNumberName]
           ,[LEABuildingSiteNumber]
           ,[LEACity]
           ,[LEAStateAbbreviation]
           ,[LEAPostalCode]
           ,[LEANameOfCounty]
           ,[LEAMainInstitutionTelephone]
           ,[LEAInstitutionFax]
           ,[LEAWebSite]
           ,[LEASuperintendentName]
           ,[LEASuperintendentElectronicMailAddress])

SELECT [SchoolId]
           ,[NameOfInstitution]
           ,[StreetNumberName]
           ,[BuildingSiteNumber]
           ,[City]
           ,[StateAbbreviation]
           ,[PostalCode]
           ,[NameOfCounty]
           ,[MainInstitutionTelephone]
           ,[InstitutionFax]
           ,[WebSite]
           ,[PrincipalName]
           ,[PrincipalElectronicMailAddress]
           ,[GradeLevels]
           ,[AccreditationStatus]
           ,[LocalEducationAgencyId]
           ,[LEANameOfInstitution]
           ,[LEAStreetNumberName]
           ,[LEABuildingSiteNumber]
           ,[LEACity]
           ,[LEAStateAbbreviation]
           ,[LEAPostalCode]
           ,[LEANameOfCounty]
           ,[LEAMainInstitutionTelephone]
           ,[LEAInstitutionFax]
           ,[LEAWebSite]
           ,[LEASuperintendentName]
           ,[LEASuperintendentElectronicMailAddress]
FROM [' + @OdsDatabaseReference + '].[cmp].[SchoolDimension]'

EXEC(@sqlCmd)

