CREATE TABLE [cmp].[SchoolDimension] (
    [SchoolKey]                              INT            NOT NULL,
    [NameOfInstitution]                      NVARCHAR (75)  NOT NULL,
    [StreetNumberName]                       NVARCHAR (150) NOT NULL,
    [BuildingSiteNumber]                     NVARCHAR (20)  NULL,
    [City]                                   NVARCHAR (30)  NOT NULL,
    [StateAbbreviation]                      NVARCHAR (2)   NOT NULL,
    [PostalCode]                             NVARCHAR (17)  NOT NULL,
    [NameOfCounty]                           NVARCHAR (30)  NOT NULL,
    [MainInstitutionTelephone]               NVARCHAR (24)  NOT NULL,
    [InstitutionFax]                         NVARCHAR (24)  NOT NULL,
    [WebSite]                                NVARCHAR (255) NOT NULL,
    [PrincipalName]                          NVARCHAR (182) NOT NULL,
    [PrincipalElectronicMailAddress]         NVARCHAR (128) NOT NULL,
    [GradeLevels]                            NVARCHAR (10)  NOT NULL,
    [AccreditationStatus]                    NVARCHAR (75)  NULL,
    [LocalEducationAgencyKey]                INT            NOT NULL,
    [LEANameOfInstitution]                   NVARCHAR (75)  NOT NULL,
    [LEAStreetNumberName]                    NVARCHAR (150) NOT NULL,
    [LEABuildingSiteNumber]                  NVARCHAR (20)  NULL,
    [LEACity]                                NVARCHAR (30)  NOT NULL,
    [LEAStateAbbreviation]                   NVARCHAR (2)   NOT NULL,
    [LEAPostalCode]                          NVARCHAR (17)  NOT NULL,
    [LEANameOfCounty]                        NVARCHAR (30)  NOT NULL,
    [LEAMainInstitutionTelephone]            NVARCHAR (24)  NOT NULL,
    [LEAInstitutionFax]                      NVARCHAR (24)  NOT NULL,
    [LEAWebSite]                             NVARCHAR (255) NOT NULL,
    [LEASuperintendentName]                  NVARCHAR (182) NOT NULL,
    [LEASuperintendentElectronicMailAddress] NVARCHAR (128) NOT NULL,
    CONSTRAINT [PK_SchoolDimension] PRIMARY KEY CLUSTERED ([SchoolKey] ASC)
);

